import type { Metadata } from "next";

export function generateSEOMetadata(
  title = "ArraysID Next Starterkit",
  description = "Generated by arrays.id",
) {
  const metadata: Metadata = {
    title,
    description,
    icons: [{ rel: "icon", url: "/favicon.ico" }],
  };

  return metadata;
}
