import "@/styles/globals.css";

import { type Metadata } from "next";

import { geist } from "@/lib/fonts";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "ArraysID Next Starterkit",
  description: "Generated by arrays.id",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
